Update rspec-core to 3.4.4
Hopefully this will fix:

```
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x0000000001d4ea08>
/home/circleci/project/vendor/bundle/gems/rspec-core-3.4.2/lib/rspec/core/rake_task.rb:91:in `define'
/home/circleci/project/vendor/bundle/gems/rspec-core-3.4.2/lib/rspec/core/rake_task.rb:71:in `initialize'
/home/circleci/project/vendor/bundle/gems/rspec-rails-3.4.2/lib/rspec/rails/tasks/rspec.rake:11:in `new'
/home/circleci/project/vendor/bundle/gems/rspec-rails-3.4.2/lib/rspec/rails/tasks/rspec.rake:11:in `<top (required)>'
/home/circleci/project/vendor/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/circleci/project/vendor/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/home/circleci/project/vendor/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/circleci/project/vendor/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/circleci/project/vendor/bundle/gems/rspec-rails-3.4.2/lib/rspec-rails.rb:19:in `block in <class:Railtie>'
/home/circleci/project/vendor/bundle/gems/railties-4.2.10/lib/rails/railtie.rb:237:in `instance_exec'
/home/circleci/project/vendor/bundle/gems/railties-4.2.10/lib/rails/railtie.rb:237:in `block in run_tasks_blocks'
/home/circleci/project/vendor/bundle/gems/railties-4.2.10/lib/rails/railtie.rb:245:in `each'
/home/circleci/project/vendor/bundle/gems/railties-4.2.10/lib/rails/railtie.rb:245:in `each_registered_block'
/home/circleci/project/vendor/bundle/gems/railties-4.2.10/lib/rails/railtie.rb:237:in `run_tasks_blocks'
/home/circleci/project/vendor/bundle/gems/railties-4.2.10/lib/rails/application.rb:451:in `block in run_tasks_blocks'
/home/circleci/project/vendor/bundle/gems/railties-4.2.10/lib/rails/engine/railties.rb:13:in `each'
/home/circleci/project/vendor/bundle/gems/railties-4.2.10/lib/rails/engine/railties.rb:13:in `each'
/home/circleci/project/vendor/bundle/gems/railties-4.2.10/lib/rails/application.rb:451:in `run_tasks_blocks'
/home/circleci/project/vendor/bundle/gems/railties-4.2.10/lib/rails/engine.rb:453:in `load_tasks'
/home/circleci/project/Rakefile:7:in `<top (required)>'
/home/circleci/project/vendor/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
(See full trace by running task with --trace)
Exited with code 1
```